# Generated by Django 4.0.5 on 2023-02-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bags', models.IntegerField()),
                ('weight_kgs', models.IntegerField()),
                ('commission', models.FloatField()),
                ('labour_cost', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
